AWSTemplateFormatVersion: '2010-09-09'
Description: Template S3 copy batch operation

Parameters:
  S3BatchReportBucketName:
    Description: S3 Batch report bucket name
    Type: String
    Default: "batch-report-operation"

  S3BatchSourceBucketName:
    Description: S3 Batch report bucket name
    Type: String
    Default: "batch-source-operation"

  S3BatchTargetBucketName:
    Description: S3 Batch report bucket name
    Type: String
    Default: "batch-target-operation"

Resources:
  S3BatchReportBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BatchReportBucketName

  S3BatchSourceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BatchSourceBucketName

  S3BatchTargetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BatchTargetBucketName

  S3BatchOperationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "s3-batch-operation"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - batchoperations.s3.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: S3BatchOperationPolicies
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:GetBucketLocation
                Resource: !Join [ "", [ "arn:aws:s3:::", !Ref S3BatchReportBucketName, "/*" ] ]
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketLocation
                Resource: !Join [ "", [ "arn:aws:s3:::", !Ref S3BatchSourceBucketName, "/manifest.csv" ] ]
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketLocation
                Resource: !Join [ "", [ "arn:aws:s3:::", !Ref S3BatchSourceBucketName, "/*" ] ]
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetBucketLocation
                Resource: !Join [ "", [ "arn:aws:s3:::", !Ref S3BatchTargetBucketName, "/*" ] ]

Outputs:
  S3BatchReportBucketName:
    Value: !Ref S3BatchReportBucket
    Description: Name of S3 batch report bucket

  S3BatchSourceBucketName:
    Value: !Ref S3BatchSourceBucket
    Description: Name of S3 batch source bucket

  S3BatchTargetBucketName:
    Value: !Ref S3BatchTargetBucket
    Description: Name of S3 batch targer bucket

  S3BatchOperationRoleARN:
    Value: !GetAtt [S3BatchOperationRole, Arn]
    Description: ARN of batch operation role